import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { ThemeModeProvider } from '@/components/ThemeContext';
import Header from '@/components/Header';
import Sidebar from '@/components/Dashboard/Sidebar';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeModeProvider>
          <Header />
          <div className="flex">
            <Sidebar />
            {children}
          </div>
        </ThemeModeProvider>
      </body>
    </html>
  );
}
